### ISSUE TITLE
GCP-PROD-ERROR: UnknownHostException: content.bufdir.no

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/fdk-concept-harvester#112]
Lenke til GCP log: [https://console.cloud.google.com/errors/detail/CJOlvPyRiMneUw;time=P1D?project=digdir-fdk-prod](https://console.cloud.google.com/errors/detail/CJOlvPyRiMneUw;time=P1D?project=digdir-fdk-prod)

![image.png](https://images.zenhubusercontent.com/621e2fbb9626c4acaf8af241/1fbcfe90-15cb-4d8d-aa7f-91d112f7a839)

**Comment by valosnah** [comment]
Tenker dette bare var en forbigående hikke hos bufdir. Kun observert denne ene gangen, lukkes.
