### ISSUE TITLE
Harvest of skatteetaten begrep fails

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-concept-harvester#126]
> org.apache.jena.riot.RiotException: [line: 1, col: 20] Triples not terminated by DOT
> 	at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.fatal(ErrorHandlerFactory.java:167)
> 	at org.apache.jena.riot.lang.LangEngine.raiseException(LangEngine.java:148)
> 	at org.apache.jena.riot.lang.LangEngine.exceptionDirect(LangEngine.java:143)
> 	at org.apache.jena.riot.lang.LangEngine.exception(LangEngine.java:137)
> 	at org.apache.jena.riot.lang.LangEngine.expect(LangEngine.java:130)
> 	at org.apache.jena.riot.lang.LangEngine.expectOrEOF(LangEngine.java:119)
> 	at org.apache.jena.riot.lang.LangTurtleBase.expectEndOfTriplesTurtle(LangTurtleBase.java:329)
> 	at org.apache.jena.riot.lang.LangTurtle.expectEndOfTriples(LangTurtle.java:51)
> 	at org.apache.jena.riot.lang.LangTurtleBase.triples(LangTurtleBase.java:315)
> 	at org.apache.jena.riot.lang.LangTurtleBase.triplesSameSubject(LangTurtleBase.java:178)
> 	at org.apache.jena.riot.lang.LangTurtle.oneTopLevelElement(LangTurtle.java:46)
> 	at org.apache.jena.riot.lang.LangTurtleBase.runParser(LangTurtleBase.java:79)
> 	at org.apache.jena.riot.lang.LangBase.parse(LangBase.java:43)
> 	at org.apache.jena.riot.RDFParserRegistry$ReaderRIOTLang.read(RDFParserRegistry.java:209)
> 	at org.apache.jena.riot.RDFParser.read(RDFParser.java:420)
> 	at org.apache.jena.riot.RDFParser.parseNotUri(RDFParser.java:406)
> 	at org.apache.jena.riot.RDFParser.parse(RDFParser.java:356)
> 	at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:570)
> 	at org.apache.jena.riot.RDFDataMgr.parseFromReader(RDFDataMgr.java:728)
> 	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:287)
> 	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:271)
> 	at org.apache.jena.riot.adapters.RDFReaderRIOT.read(RDFReaderRIOT.java:62)
> 	at org.apache.jena.rdf.model.impl.ModelCom.read(ModelCom.java:246)
> 	at no.fdk.fdk_concept_harvester.rdf.RDFUtilsKt.parseRDFResponse(RDFUtils.kt:37)
> 	at no.fdk.fdk_concept_harvester.harvester.ConceptHarvester.harvestConceptCollectionFromRDF(ConceptHarvester.kt:100)
> 	at no.fdk.fdk_concept_harvester.harvester.ConceptHarvester.harvestConceptCollection(ConceptHarvester.kt:54)
> 	at no.fdk.fdk_concept_harvester.harvester.HarvesterActivity$initiateHarvest$1$1$3$1.invokeSuspend(HarvesterActivity.kt:45)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
> Harvest of https://data.skatteetaten.no/begrep/ failed

**Comment by KjerstiSteien** [comment]
Ikke lenger relevant, da skatteetaten har flyttet begrepene sine til registreringsløsningen til Felles datakatalog.
