### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-concept-harvester#13]
Denne tapetserer loggen og kjem frå 
no.ccat.service.RDFToModelTransformer.directlyExtractSources(RDFToModelTransformer.java:134)

Log: 
https://console.cloud.google.com/logs/viewer?project=fdk-prod&authuser=1&organizationId=382284307604&minLogLevel=0&expandAll=false&timestamp=2019-12-04T10:57:34.116000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeStart=2019-12-04T09:14:38.263Z&interval=PT1H&resource=k8s_container%2Fcluster_name%2Ffdk-prod%2Fnamespace_name%2Fprod%2Fcontainer_name%2Fconcept-cat&scrollTimestamp=2019-12-04T10:13:02.232912176Z&dateRangeUnbound=forwardInTime

Vi må finne ut kvifor dette skjer, skrive ein test som gjenskaper denne, og rette feilen. 

Forvørig burde vi ikkje logge slike exceptions som info.

**Comment by sindresandvik2** [comment]
Allerede prodsatt!
