### ISSUE TITLE
Støtte markdown på lenker i kildefeltet til begrepskatalogen ved høsting fra virksomhetene

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-concept-harvester#17]
@marittor commented on [Tue Dec 10 2019](https://github.com/Informasjonsforvaltning/fdk/issues/2895)

Ønsker støtte for markdown på lenker i kildefeltet, også ved høsting av begrepsbeskrivelser fra virksomhetene. Det er støtte før dette idag for det som kommer ut i portal gjennom registreringsløsningen for begrep, men ser ikke ut til å være det for det som kommer inn via høsting.. 

Se eksempel på hvordan kildefeltet til begreper som kommer fra registreringsløsningen ser ut: https://fellesdatakatalog.brreg.no/concepts/0d0ec0b9-abb4-4344-8a31-d1e8fe673043 

Kan vi få det som høstes til også å se slik ut? 

Forretningsverdi: Mindre viktig

**Comment by jeffreiffers** [comment]
@stigbd Er denne fremdeles relevant?

**Comment by KjerstiSteien** [comment]
Lukker denne til behovet eventuelt meldes inn på nytt.
