### ISSUE TITLE
Hente ut både betydningsbeskrivelse og definisjon som temporær fiks i concept-harvester

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-concept-harvester#51]
@lillelars commented on [Mon Apr 27 2020](https://github.com/Informasjonsforvaltning/fdk/issues/3093)

**Comment by stigbd** [comment]
Akseptansekriterium:
at definisjonen til et begrep med skosno:definisjon blir tilgjengelig i fdk-concept-harvester API:
feks
```
curl -H "Accept: application/json" "https://fellesdatakatalog.digdir.no/api/concepts/c846ba3b-1c21-4ec1-8849-aa87cfca1689"
```

**Comment by lillelars** [comment]
Testet og verifisert av Stig. Lukker denne.
