### ISSUE TITLE
Eksponere Felles begrepskatalog som SKOS-AP-NO

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-concept-harvester#63]
Hentet fra behov: https://github.com/Informasjonsforvaltning/behov/issues/342

- [x] Ny høster kjører 
- [x] Høster skal svare med RDF
- [x] Gjøre klar etl
- [x] Håndtering av data fra skatt (opprette eget issue @lillelars )
- [x] Kjøre etl i alle miljø (Skatt sine begreper blokkerer)
- [x] fulltext og harvester-bff bruker ny høster (Skatt sine begreper blokkerer)

**Comment by lillelars** [comment]
@stigbd avhenger nå av at vi tar tak i Skatt sine begreper før vi tar dette videre.

**Comment by shenluna** [comment]
Testet OK
